apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-model-inference
  namespace: airflow
spec:
  type: Python
  pythonVersion: "3"
  sparkVersion: "3.5.0"
  mode: cluster

  image: "spark-demo:v1.0"
  imagePullPolicy: Never
  mainApplicationFile: local:///app/inference.py

  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: spark-operator
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.5.0