airflow:
  webserverSecretKey: admin

  defaultAirflowTag: "2.6.0"
  airflowVersion: "2.6.0"
  dags:
    gitSync:
      enabled: true
      repo: https://github.com/iAlexMlops/airflow-spark-demo.git
      branch: main

      subPath: "dags"
      period: 15s
      wait: ~

      containerName: git-sync
