airflow:
#  images:
#    airflow:
#      repository: airflow
#      tag: fix-v2

  defaultAirflowTag: "2.8.1"
  airflowVersion: "2.8.1"

  webserverSecretKey: admin

  dags:
    persistence:
      enabled: true
    gitSync:
      enabled: true
      repo: https://github.com/iAlexMlops/airflow-spark-demo.git
      branch: main

      subPath: "dags"
      period: 15s

      containerName: git-sync
