airflow:
  webserverSecretKey: admin

  defaultAirflowTag: "2.5.3"
  airflowVersion: "2.5.3"
  dags:
    gitSync:
      enabled: true
      repo: https://github.com/iAlexMlops/airflow-spark-demo.git
      branch: main
      subPath: "dags"
      wait: 15
      containerName: git-sync
